# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='okpo',
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='korr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корр. счет'),
        ),
    ]
