# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_auto_20160831_0933'),
        ('advertisers', '0003_merchant'),
    ]

    operations = [
    ]
