# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_merge_20160831_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
