# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0019_auto_20161102_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='was_mailed',
            field=models.BooleanField(default=False),
        ),
    ]
