# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('url', models.URLField(max_length=160, verbose_name='URL')),
                ('image', models.ImageField(max_length=250, upload_to='partners', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
                'verbose_name': 'Партнер',
            },
        ),
    ]
