# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20161108_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(max_length=250, upload_to='partners', verbose_name='Изображение'),
        ),
    ]
