# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20161020_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
