# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('organization_name', models.CharField(max_length=120, verbose_name='Название организации')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('status', models.IntegerField(choices=[(0, 'Новая'), (1, 'Принята'), (2, 'Отклонена')], default=0, verbose_name='Статус')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Заявка от рекламодателя',
                'verbose_name_plural': 'Заявки от рекламодателей',
            },
        ),
    ]
