# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 08:52
from __future__ import unicode_literals

from django.db import migrations


def calculate_max_values(apps, schema_editor):
    Option = apps.get_model('promo', 'Option')
    Option.objects.filter(tech_name='cat_background').update(max_count=None)


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20161004_1007'),
    ]

    operations = [
        migrations.RunPython(calculate_max_values, migrations.RunPython.noop),
    ]
