# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 13:55
from __future__ import unicode_literals

from django.db import migrations

from django.conf import settings


def forwards(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Category.objects.get_or_create(name=settings.DEFAULT_CATEGORY_NAME, slug=settings.DEFAULT_CATEGORY_SLUG)


def backwards(apps, schema_editor):
    # allow backwards migration but do nothing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards),
    ]
