# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160902_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
