# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
