# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160906_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='datetime_created',
            new_name='created_datetime',
        ),
    ]
