# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0012_merge_20161010_1035'),
        ('catalog', '0008_auto_20160927_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='advertisers.Merchant'),
        ),
    ]
