# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161010_1054'),
        ('catalog', '0009_category_merchant'),
    ]

    operations = [
    ]
