# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('tech_name', models.SlugField(unique=True, verbose_name='Техническое название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('max_count', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательна для пакета')),
                ('is_boolean', models.BooleanField(default=False, verbose_name='Логическая')),
                ('image', models.ImageField(upload_to='promo', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тарифная опция',
                'verbose_name_plural': 'Тарифные опции',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Кастомный пакет')),
            ],
            options={
                'verbose_name': 'Рекламный пакет',
                'verbose_name_plural': 'Рекламные пакеты',
            },
        ),
        migrations.CreateModel(
            name='PromoOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Значение')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='promo.Option')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='promo.Promo')),
            ],
            options={
                'verbose_name': 'Подключенная тарифная опция',
                'verbose_name_plural': 'Подключенные тарифные опции',
            },
        ),
        migrations.AlterUniqueTogether(
            name='promooption',
            unique_together=set([('promo', 'option')]),
        ),
    ]
