# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='available_options',
            field=models.ManyToManyField(related_name='available_in_promos', to='promo.Option', verbose_name='Доступные опции'),
        ),
    ]
