# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_auto_20161011_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
    ]
