# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.IntegerField(choices=[(0, 'Не оплачен'), (1, 'Оплачен'), (2, 'Отменен')], default=0, verbose_name='Статус')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.Promo', verbose_name='Промо')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.Invoice', verbose_name='Счёт')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.Option', verbose_name='Опция')),
            ],
        ),
    ]
