# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0006_merge_20160907_1251'),
        ('orders', '0002_auto_20160908_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='invoice',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='advertisers.Merchant', verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
