# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160914_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_invoices', to='promo.Option', verbose_name='Опция'),
        ),
    ]
