# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:17
from __future__ import unicode_literals

import apps.orders.models
from django.db import migrations, models
from django.utils import timezone


def migrate_status(apps, schema_editor):
    Invoice = apps.get_model('orders', 'Invoice')

    from apps.orders.models import InvoiceStatus
    Invoice.objects.filter(status=InvoiceStatus.paid).update(is_paid=True)
    Invoice.objects.filter(status=InvoiceStatus.cancelled).update(expired_datetime=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160920_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expired_datetime',
            field=models.DateTimeField(default=apps.orders.models.get_default_expiration_date, verbose_name='Срок истечения'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.RunPython(
            migrate_status,
            migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
