# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160923_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Сумма в рублях'),
        ),
    ]
