# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_auto_20161031_1005'),
        ('advertisers', '0021_auto_20161116_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_shown', models.IntegerField(default=0)),
                ('times_clicked', models.IntegerField(default=0)),
                ('banner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisers.Banner')),
            ],
        ),
        migrations.CreateModel(
            name='LogoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_shown', models.IntegerField(default=0)),
                ('times_clicked', models.IntegerField(default=0)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisers.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TeaserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_shown', models.IntegerField(default=0)),
                ('times_clicked', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
