# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0006_merge_20160907_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='image',
        ),
    ]
