# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0008_merchant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='banners.Partner', verbose_name='Партнеры'),
        ),
    ]
