# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20160927_0525'),
        ('mediafiles', '0001_initial'),
        ('advertisers', '0009_auto_20160923_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Супербаннер'), (10, 'Акционный баннер'), (20, 'Вертикальный баннер'), (30, 'Фон слева'), (40, 'Фон справа')])),
                ('url', models.URLField()),
                ('on_main', models.BooleanField(default=False)),
                ('in_mailing', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='banners', to='catalog.Category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='mediafiles.Image')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='advertisers.Merchant')),
            ],
        ),
    ]
