# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='in_mailing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='on_main',
            field=models.BooleanField(),
        ),
    ]
