# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20160927_0525'),
        ('advertisers', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='logo_categories',
            field=models.ManyToManyField(related_name='merchant_logos', to='catalog.Category'),
        ),
    ]
