# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0011_merchant_logo_categories'),
        ('advertisers', '0011_advertiserprofile_inner'),
    ]

    operations = [
    ]
