# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0011_auto_20161010_1102'),
        ('advertisers', '0012_merge_20161010_1035'),
    ]

    operations = [
    ]
