# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


def set_advertiser_type(apps, schema_editor):
    AdvertiserProfile = apps.get_model('advertisers', 'AdvertiserProfile')
    for type, inner in [(10, 'АКИТ'), (11, 'AdmitAd'), (12, 'Партнеры')]:
        AdvertiserProfile.objects.filter(inner=inner).update(type=type)


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0013_merge_20161011_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Обычный'), (10, 'АКИТ'), (11, 'AdmitAd'), (12, 'Партнеры'), (20, 'Сверхновая')], default=0),
        ),
        migrations.RunPython(set_advertiser_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='inner',
        ),
    ]
