# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0014_auto_20161012_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Обычный'), (10, 'АКИТ'), (11, 'AdmitAd'), (12, 'Партнёры'), (20, 'Сверхновая')], default=0),
        ),
    ]
