# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0016_merchant_receives_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='last_save',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
