# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0017_merchant_last_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='receives_notifications',
            field=models.BooleanField(default=True, verbose_name='Получает уведомления'),
        ),
    ]
