# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0018_auto_20161031_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='banner_mailings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='superbanner_mailings_count',
            field=models.IntegerField(default=0),
        ),
    ]
