# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0021_auto_20161116_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.TextField(),
        ),
    ]
