# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0021_auto_20161116_1218'),
        ('advertisers', '0023_auto_20161118_1553'),
    ]

    operations = [
    ]
