# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160922_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='datetime_created',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='datetime_updated',
            new_name='updated_datetime',
        ),
    ]
