# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20160923_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landinglogo',
            options={'ordering': ('position',), 'verbose_name': 'Лого', 'verbose_name_plural': 'Лого'},
        ),
    ]
