# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20160923_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landinglogo',
            options={},
        ),
        migrations.AlterField(
            model_name='landinglogo',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
