# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20161004_1135'),
        ('landing', '0005_auto_20161012_1514'),
    ]

    operations = [
    ]
