# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:51
from __future__ import unicode_literals

from django.db import migrations
import functools
import libs.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_merge_20161020_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinglogo',
            name='image',
            field=libs.db.fields.ResizedImageField(upload_to=functools.partial(libs.db.fields._update_filename, *(), **{'path': 'landing-logos'}), verbose_name='Изображение'),
        ),
    ]
