# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 14:07
from __future__ import unicode_literals

from django.db import migrations
import libs.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20161108_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinglogo',
            name='image',
            field=libs.db.fields.ResizedImageField(upload_to='landing-logos', verbose_name='Изображение'),
        ),
    ]
