# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160823_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Verification'), (2, 'Registration')], default=0, verbose_name='Тип'),
        ),
    ]
