# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:51
from __future__ import unicode_literals

import apps.specials.models
from django.db import migrations, models
import functools
import libs.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_auto_20161012_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='document',
            field=models.FileField(upload_to=functools.partial(libs.db.fields._update_filename, *(), **{'path': 'specials'}), validators=[apps.specials.models.validate_file_extension]),
        ),
    ]
