# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import libs.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20160824_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(max_length=250, upload_to=functools.partial(libs.db.fields._update_filename, *(), **{'path': 'partners'}), verbose_name='Изображение'),
        ),
    ]
