# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_20161011_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='advertisers.Merchant'),
        ),
    ]
