# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_advertiserrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserrequest',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='advertiserrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='advertiserrequest',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='advertiserrequest',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
