# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0004_auto_20160923_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserrequest',
            name='user_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
