# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20160926_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='join_mnogo_ru',
            field=models.BooleanField(default=False),
        ),
    ]
